# Generated by Django 4.0.1 on 2022-02-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='bool',
            new_name='book',
        ),
    ]
